[package]
name = "library-loader"
version = "0.1.0"
authors = ["Edwin Svensson <git@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
base64 = "0.10.1"
# zlib = "0.0.1"
clap = { version = "2.33.0", features = ["yaml"] }
